#!/bin/bash
# entrypoint.sh — Container PID 1 für mc-kimi-agent
# Window 0: kimi interaktiv (User sieht CLI-Header + Prompt live)
# Window 1: poll.sh pollt Tasks und sendet sie via tmux send-keys an Window 0
#
# Unterschiede zu mc-claude-agent/entrypoint.sh:
#   - Auth: Kimi-OAuth lebt als credentials/-Dateien im gemounteten
#     KIMI_CODE_HOME (kein Env-Token — Kimi kennt keinen langlebigen Token,
#     und Credentials-Kopien sterben an der Refresh-ROTATION, Spike 2026-07-24).
#     Fehlende Credentials sind KEIN Startabbruch: die TUI startet trotzdem,
#     Mark macht einmalig /login (Device-Code) im Sessions-Terminal.
#   - config.toml (Hooks + Defaults) wird hier idempotent geschrieben —
#     credentials/ wird NIE angefasst.
#   - tmux braucht `extended-keys on`, sonst submittet Enter in der kimi-TUI
#     NICHT (Spike 2026-07-24 — die TUI warnt selbst im Banner).
#   - Kein recycler-Window (claude-mem-spezifisch).

SESSION="${AGENT_NAME:-agent}"
KIMI_HOME="${KIMI_CODE_HOME:-/home/agent/.kimi-code}"

# ── Bootstrap: Tokens vom Backend holen (Vault-dekryptiert) ──
BOOTSTRAP_URL="${MC_API_URL:-http://backend:8000}/api/v1/internal/bootstrap?agent_name=${AGENT_NAME}"
BOOTSTRAP_RESPONSE=""
for _attempt in 1 2 3 4 5 6; do
    BOOTSTRAP_RESPONSE=$(curl -sf --max-time 5 "$BOOTSTRAP_URL" 2>/dev/null) && break
    echo "[entrypoint] Bootstrap Versuch $_attempt fehlgeschlagen, retry in 3s..."
    sleep 3
done

if [ -n "$BOOTSTRAP_RESPONSE" ]; then
    _EXPORTS=$(echo "$BOOTSTRAP_RESPONSE" | python3 -c '
import sys, json
try:
    d = json.load(sys.stdin)
    for k, v in d.items():
        if k in ("MC_AGENT_TOKEN", "GH_TOKEN", "CONTEXT_MAX"):
            print(f"{k}={v}")
except Exception:
    sys.exit(1)
' 2>/dev/null)
    if [ $? -eq 0 ] && [ -n "$_EXPORTS" ]; then
        _NEW_TOKEN=$(echo "$_EXPORTS" | grep '^MC_AGENT_TOKEN=' | cut -d= -f2-)
        _NEW_GH_TOKEN=$(echo "$_EXPORTS" | grep '^GH_TOKEN=' | cut -d= -f2-)
        _NEW_CONTEXT_MAX=$(echo "$_EXPORTS" | grep '^CONTEXT_MAX=' | cut -d= -f2-)
        if [ -n "$_NEW_TOKEN" ]; then
            export MC_AGENT_TOKEN="$_NEW_TOKEN"
            export MC_TOKEN="$_NEW_TOKEN"
        else
            export MC_AGENT_TOKEN="${MC_TOKEN:-}"
        fi
        # Kimi K3 hat ein 1M-Fenster — CONTEXT_MAX kommt aus der DB
        # (agent.context_max), Fallback grosszügig.
        export CONTEXT_MAX="${_NEW_CONTEXT_MAX:-${CONTEXT_MAX:-1000000}}"
        if [ -n "$_NEW_GH_TOKEN" ]; then
            export GH_TOKEN="$_NEW_GH_TOKEN"
            GIT_CRED_FILE="${HOME}/.git-credentials"
            echo "https://oauth:${GH_TOKEN}@github.com" > "$GIT_CRED_FILE"
            chmod 600 "$GIT_CRED_FILE"
            git config --global credential.helper "store --file=${GIT_CRED_FILE}"
            git config --global user.email "${AGENT_NAME}@mc.local"
            git config --global user.name "${AGENT_NAME}"
            echo "[entrypoint] GH_TOKEN aktiv (git credential.helper + gh CLI env)"
            if [ -d /home/agent/.git-hooks ]; then
                git config --global core.hooksPath /home/agent/.git-hooks
                echo "[entrypoint] mc pre-push guard aktiv"
            fi
        fi
        echo "[entrypoint] Bootstrap OK — MC_AGENT_TOKEN geladen"
    else
        echo "[entrypoint] Bootstrap JSON-Parse fehlgeschlagen — Fallback auf Env-Vars"
        if [ -z "${MC_TOKEN:-}" ]; then
            _agent_upper=$(printf '%s' "${AGENT_NAME:-}" | tr '[:lower:]' '[:upper:]' | tr '-' '_')
            _tok_var="MC_TOKEN_${_agent_upper}"
            eval "_tok_val=\${${_tok_var}:-}"
            if [ -n "$_tok_val" ]; then
                export MC_TOKEN="$_tok_val"
                echo "[entrypoint] MC_TOKEN resolved from ${_tok_var} (env_file fallback)"
            fi
        fi
        export MC_AGENT_TOKEN="${MC_TOKEN:-}"
    fi
else
    echo "[entrypoint] Bootstrap fehlgeschlagen — Fallback auf Env-Vars"
    if [ -z "${MC_TOKEN:-}" ]; then
        _agent_upper=$(printf '%s' "${AGENT_NAME:-}" | tr '[:lower:]' '[:upper:]' | tr '-' '_')
        _tok_var="MC_TOKEN_${_agent_upper}"
        eval "_tok_val=\${${_tok_var}:-}"
        if [ -n "$_tok_val" ]; then
            export MC_TOKEN="$_tok_val"
            echo "[entrypoint] MC_TOKEN resolved from ${_tok_var} (env_file fallback)"
        fi
    fi
    export MC_AGENT_TOKEN="${MC_TOKEN:-}"
fi

# ── Kimi-Config: config.toml idempotent schreiben (credentials/ NIE anfassen) ──
mkdir -p "$KIMI_HOME/oauth" "$KIMI_HOME/credentials"
touch "$KIMI_HOME/oauth/kimi-code"
cat > "$KIMI_HOME/config.toml" <<'KIMI_CONF'
# GENERATED by mc-kimi-agent entrypoint.sh — Hand-Edits werden beim nächsten
# Container-Start überschrieben. credentials/ bleibt unangetastet.
default_model = "kimi-code/k3"

[thinking]
enabled = true
effort = "high"

[providers."managed:kimi-code"]
type = "kimi"
api_key = ""
base_url = "https://api.kimi.com/coding/v1"

[providers."managed:kimi-code".oauth]
storage = "file"
key = "oauth/kimi-code"

# W2.1 Turn-Signal (ADR-071): UserPromptSubmit/Stop appenden
# `<epoch> submit|stop` an ~/.turn-signal — gleiche Datei + gleiches Format
# wie die claude-Harness, lib/turn-state.sh liest sie unverändert.
# Pfad absichtlich absolut UND container-lokal: ein $HOME-fremder Pfad würde
# bei mehreren Kimi-Instanzen die Signal-Dateien vermischen (Spike-Fund).
[[hooks]]
event = "UserPromptSubmit"
command = "printf '%s submit\n' \"$(date +%s)\" >> /home/agent/.turn-signal"
timeout = 5

[[hooks]]
event = "Stop"
command = "printf '%s stop\n' \"$(date +%s)\" >> /home/agent/.turn-signal"
timeout = 5
KIMI_CONF

if [ ! -s "$KIMI_HOME/credentials/kimi-code.json" ]; then
    echo "[entrypoint] WARNUNG: Keine Kimi-Credentials in $KIMI_HOME/credentials/."
    echo "[entrypoint] Einmalig im Sessions-Terminal '/login' ausführen (Device-Code-Flow)."
fi

# tmux config — extended-keys ist für kimi PFLICHT (Enter-Submit!)
cat > /home/agent/.tmux.conf <<'TMUX_CONF'
set -g mouse on
set -g aggressive-resize on
set -g history-limit 50000
set -g default-terminal "xterm-256color"
# kimi-TUI: ohne extended-keys wird der Submit-Enter verschluckt
# (Spike 2026-07-24 — die TUI warnt selbst im Banner).
set -g extended-keys on
TMUX_CONF

# W2.1 Turn-Signal: frische Signal-Datei beim Boot (Muster mc-claude-agent).
: > /home/agent/.turn-signal

start_tmux() {
    tmux new-session -d -s "$SESSION" \
        'd=2; while true; do /home/agent/start-kimi.sh; echo "[entrypoint] kimi exited, restart in ${d}s..."; sleep "$d"; d=$(( d*2 > 60 ? 60 : d*2 )); done'
    tmux new-window -t "$SESSION:1" \
        'd=2; while true; do bash /home/agent/poll.sh; echo "[entrypoint] poll.sh exited, restart in ${d}s..."; sleep "$d"; d=$(( d*2 > 60 ? 60 : d*2 )); done'
    tmux select-window -t "$SESSION:0"
}

start_tmux

restart_poll_window() {
    tmux new-window -t "$SESSION:1" \
        'd=2; while true; do bash /home/agent/poll.sh; echo "[entrypoint] poll.sh exited, restart in ${d}s..."; sleep "$d"; d=$(( d*2 > 60 ? 60 : d*2 )); done'
    echo "[watchdog] poll window (1) neugestartet"
}

restart_kimi_window() {
    tmux new-window -t "$SESSION:0" \
        'd=2; while true; do /home/agent/start-kimi.sh; echo "[entrypoint] kimi exited, restart in ${d}s..."; sleep "$d"; d=$(( d*2 > 60 ? 60 : d*2 )); done'
    echo "[watchdog] kimi window (0) neugestartet"
}

# PID 1: Watchdog — prüft alle 30s ob tmux-Session + beide Windows leben.
while true; do
    sleep 30
    if ! tmux has-session -t "$SESSION" 2>/dev/null; then
        echo "[watchdog] tmux session '$SESSION' weg — neustart"
        start_tmux
        continue
    fi
    WINDOWS=$(tmux list-windows -t "$SESSION" -F '#{window_index}' 2>/dev/null | tr '\n' ' ')
    case " $WINDOWS " in
        *" 0 "*) ;;
        *) restart_kimi_window ;;
    esac
    case " $WINDOWS " in
        *" 1 "*) ;;
        *) restart_poll_window ;;
    esac
done
