#!/usr/bin/env python3
"""Dispatch Render Profile (MEM-03 extended diagnosis).

Per the operator's discuss-phase choice: profile the agent-provisioning Jinja
render pipeline (SOUL.md.j2 et al.) to characterize WHERE template
rendering spends time after the Plan 02-02 cache fix.

NOTE — RESEARCH.md Pitfall 1: dispatch.py:_build_dispatch_message() does
NOT use Jinja (0 grep matches for jinja|render_template|get_template). The
"5-8s dispatch render" Roadmap criterion is mis-targeted at Jinja. This
script profiles the JINJA path because that's what MEM-03 actually
optimizes; the actual dispatch hotspot lives in DB queries
(_load_dispatch_context parallel asyncio.gather) and f-string assembly,
which require a running DB to profile and are deferred to Phase 3.

Diagnostic only. Phase 2 makes no commitment to fix what this reveals.

Run inside the backend venv:
  cd $HOME/Workspace/Projects/mission-control
  source backend/.venv/bin/activate
  python3 tools/dispatch-render-profile.py
"""
from __future__ import annotations

import cProfile
import io
import pstats
import sys
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = PROJECT_ROOT / ".planning" / "notes" / "dispatch-render-profile.md"

# Ensure backend/ is importable when run from repo root
sys.path.insert(0, str(PROJECT_ROOT / "backend"))

from app.models.agent import Agent  # noqa: E402
from app.services.template_renderer import (  # noqa: E402
    _get_env,
    build_agent_context,
    render_agent_file,
)


N_WARM = 100
TEMPLATES_TO_BENCH = ["SOUL.md.j2", "HEARTBEAT.md.j2", "USER.md.j2", "MEMORY.md.j2"]


def make_bench_agent() -> Agent:
    return Agent(
        id=uuid.uuid4(),
        name="bench-agent",
        role="developer",
        board_id=uuid.uuid4(),
        is_board_lead=False,
    )


def microbenchmark(template_name: str, ctx: dict) -> tuple[float, float, float]:
    """Return (first_ms, second_ms, ratio)."""
    t0 = time.perf_counter()
    render_agent_file(template_name, ctx)
    first = (time.perf_counter() - t0) * 1000

    t0 = time.perf_counter()
    render_agent_file(template_name, ctx)
    second = (time.perf_counter() - t0) * 1000

    ratio = first / max(second, 1e-9)
    return first, second, ratio


def profile_warm_renders(template_name: str, ctx: dict) -> str:
    profiler = cProfile.Profile()
    profiler.enable()
    for _ in range(N_WARM):
        render_agent_file(template_name, ctx)
    profiler.disable()
    s = io.StringIO()
    ps = pstats.Stats(profiler, stream=s).sort_stats("cumulative")
    ps.print_stats(30)
    return s.getvalue()


def env_setup_block() -> list[str]:
    env = _get_env()
    py = sys.version.split()[0]
    try:
        import jinja2
        jinja_v = jinja2.__version__
    except ImportError:
        jinja_v = "(unavailable)"
    cache_cap = getattr(env.cache, "capacity", "n/a") if env.cache else "disabled"
    return [
        "## Setup",
        "",
        f"- Python: {py}",
        f"- Jinja2: {jinja_v}",
        f"- Environment.auto_reload: {env.auto_reload}",
        f"- Environment.cache.capacity: {cache_cap}",
        f"- Templates benched: {', '.join(TEMPLATES_TO_BENCH)}",
        f"- Warm renders for cProfile: {N_WARM}",
        "",
    ]


def main() -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    now = datetime.now(timezone.utc)

    agent = make_bench_agent()
    ctx = build_agent_context(agent, agents_on_board=[])

    out = [f"# Dispatch Render Profile — {now.strftime('%Y-%m-%d %H:%M')} UTC", ""]
    out.append("Generated by `tools/dispatch-render-profile.py` (MEM-03 extended).")
    out.append("")

    out.extend(env_setup_block())

    # Microbenchmark — multiple templates
    out.append("## Microbenchmark")
    out.append("")
    out.append("| template | first (ms) | second (ms) | ratio |")
    out.append("|---|---|---|---|")
    available = []
    for t in TEMPLATES_TO_BENCH:
        try:
            first, second, ratio = microbenchmark(t, ctx)
            available.append(t)
            out.append(f"| {t} | {first:.2f} | {second:.2f} | {ratio:.1f}x |")
        except Exception as e:
            out.append(f"| {t} | _SKIPPED_ | _{type(e).__name__}_ | — |")
    out.append("")

    # cProfile — pick the first available template
    if available:
        target = available[0]
        out.append(f"## cProfile Top-30 (warm `render_agent_file({target!r})` × {N_WARM})")
        out.append("")
        out.append("```")
        out.append(profile_warm_renders(target, ctx).rstrip())
        out.append("```")
        out.append("")

    # Verdict
    out.append("## Verdict")
    out.append("")
    out.append("**Scope clarification (RESEARCH.md Pitfall 1):**")
    out.append("- This profile covers the JINJA template render path used by")
    out.append("  agent provisioning (`render_agent_file('SOUL.md.j2', ctx)`).")
    out.append("- It does NOT profile `dispatch.py:_build_dispatch_message()` —")
    out.append("  that function uses f-strings + parallel DB queries via")
    out.append("  `_load_dispatch_context()` and is the actual source of the")
    out.append("  reported 5-8s dispatch latency.")
    out.append("- After Plan 02-02 (Jinja cache config), the Jinja path is")
    out.append("  measured here. Whatever the cumulative-time top-30 reveals")
    out.append("  is a Phase 3 / follow-up candidate, NOT a Phase 2 fix.")
    out.append("")
    out.append("**Hotspot identification:**")
    out.append("Read the cProfile top-30 above. The function with the highest")
    out.append("cumulative time (excluding `render_agent_file` itself, which is")
    out.append("the entry point) is the named hotspot. Document the function")
    out.append("name + module path in `02-05-SUMMARY.md`.")
    out.append("")
    out.append("**Phase 3 follow-up:**")
    out.append("To profile the actual dispatch hotspot, a future plan should")
    out.append("(a) build a representative DB fixture, (b) async-run")
    out.append("`_build_dispatch_message(task, agent)` with cProfile, (c)")
    out.append("compare cumulative time of `_load_dispatch_context` parallel")
    out.append("queries vs the f-string assembly.")
    out.append("")

    OUTPUT.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {OUTPUT} ({len(open(OUTPUT).read())} chars)", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
