// Mirror of backend/app/scopes.py (Scope enum + DEFAULT_SCOPES, verified
// 2026-07-10). Kept in sync manually; the wizard pre-fills from these, the
// backend (`get_agent_effective_scopes`) is the actual enforcer. Note: there
// are 21 scopes today, not 16 — scopes.py grew credentials/vault/telegram
// scopes after the original 16-scope design.

export const ALL_SCOPES: string[] = [
  "tasks:read",
  "tasks:write",
  "tasks:create",
  "tasks:manage",
  "knowledge:read",
  "knowledge:write",
  "memory:read",
  "memory:write",
  "approvals:create",
  "chat:write",
  "agents:manage",
  "content:submit",
  "heartbeat",
  "deploy:execute",
  "project:read",
  "project:write",
  "tasks:help",
  "credentials:read",
  "vault:read",
  "vault:write",
  "telegram:send",
];

export const ROLE_DEFAULT_SCOPES: Record<string, string[]> = {
  lead: ALL_SCOPES,
  orchestrator: ALL_SCOPES,
  relay: ALL_SCOPES,
  developer: [
    "tasks:read",
    "tasks:write",
    "knowledge:read",
    "knowledge:write",
    "memory:read",
    "memory:write",
    "approvals:create",
    "chat:write",
    "heartbeat",
    "project:read",
    "project:write",
    "tasks:help",
    "credentials:read",
    "vault:read",
    "vault:write",
  ],
  reviewer: [
    "tasks:read",
    "tasks:write",
    "knowledge:read",
    "knowledge:write",
    "memory:read",
    "approvals:create",
    "chat:write",
    "heartbeat",
    "tasks:help",
    "vault:read",
  ],
  planner: [
    "tasks:read",
    "knowledge:read",
    "knowledge:write",
    "memory:write",
    "approvals:create",
    "chat:write",
    "heartbeat",
    "project:read",
    "project:write",
    "tasks:help",
    "vault:read",
    "vault:write",
  ],
  researcher: [
    "tasks:read",
    "tasks:write",
    "knowledge:read",
    "knowledge:write",
    "memory:read",
    "memory:write",
    "chat:write",
    "content:submit",
    "heartbeat",
    "project:read",
    "project:write",
    "tasks:help",
    "vault:read",
    "vault:write",
  ],
  writer: [
    "tasks:read",
    "tasks:write",
    "knowledge:read",
    "memory:read",
    "chat:write",
    "content:submit",
    "heartbeat",
    "tasks:help",
    "vault:read",
    "vault:write",
  ],
  tester: [
    "tasks:read",
    "tasks:write",
    "knowledge:read",
    "knowledge:write",
    "memory:write",
    "chat:write",
    "heartbeat",
    "tasks:help",
    "credentials:read",
  ],
  deployer: [
    "tasks:read",
    "tasks:write",
    "knowledge:read",
    "knowledge:write",
    "memory:write",
    "chat:write",
    "heartbeat",
    "deploy:execute",
    "tasks:help",
    "credentials:read",
    "vault:read",
    "vault:write",
  ],
};

export function defaultScopesForRole(role: string | null, isLead: boolean): string[] {
  if (isLead) return [...ALL_SCOPES];
  const key = (role ?? "").toLowerCase();
  return [...(ROLE_DEFAULT_SCOPES[key] ?? ALL_SCOPES)];
}
