#!/bin/bash
# entrypoint.sh — Kimi-Host-Agent (launchd com.mc.kimi-host).
#
# Kimi Code CLI als Host-Agent nach dem Boss-Host-Muster: tmux-Session
# 'kimi-host' mit Window 0 = kimi-TUI (start-kimi-host.sh in Restart-Loop)
# und Window 1 = der GETEILTE poll.sh (docker/shared/poll.sh) mit den
# TCK-geprüften Adapter-Libs aus dem Repo-Checkout — keine Host-Kopien.
#
# Unterschiede zum Container (docker/mc-kimi-agent/entrypoint.sh):
#   - Kein Backend-Bootstrap-HTTP: Token kommt aus agent.env
#     (~/.mc/agents/kimi/agent.env, geschrieben von bootstrap_kimi_agent).
#   - KIMI_CODE_HOME = ~/.mc/agents/kimi/kimi-config — bewusst GETRENNT von
#     Marks interaktivem ~/.kimi-code: eigener Device-Code-Login (einmalig
#     /login im Sessions-Terminal) und eigene Hook-Config. Marks config.toml
#     wird NIE angefasst; die Turn-Signal-Hooks landen nur in der Agent-Config
#     und schreiben nach ~/.mc/agents/kimi/.turn-signal (nicht /home/agent!).
#   - Default-tmux-Server (kein eigener Socket) — die Sessions-Seite mountet
#     die Session über _HOST_AGENT_TMUX_TARGETS["kimi"].

set -eu

BASE="$HOME/.mc/agents/kimi"
REPO="${MC_REPO_PATH:-$HOME/Workspace/Projects/mission-control}"
SESSION="kimi-host"
KIMI_HOME="$BASE/kimi-config"

mkdir -p "$BASE/logs" "$KIMI_HOME/oauth" "$KIMI_HOME/credentials" \
         "$HOME/.mc/workspaces/kimi"
touch "$KIMI_HOME/oauth/kimi-code"

# agent.env sourcen (MC_AGENT_TOKEN, MC_API_URL, …)
ENV_FILE="$BASE/agent.env"
if [ -f "$ENV_FILE" ]; then
    set -a
    # shellcheck disable=SC1090
    . "$ENV_FILE"
    set +a
fi

# Kimi-Binary: Host-Install (~/.kimi-code/bin/kimi via install.sh) oder PATH.
KIMI_BIN="$(command -v kimi || true)"
[ -n "$KIMI_BIN" ] || KIMI_BIN="$HOME/.kimi-code/bin/kimi"
if [ ! -x "$KIMI_BIN" ]; then
    echo "[kimi-host] FEHLER: kimi-Binary nicht gefunden ($KIMI_BIN)." >&2
    echo "[kimi-host] Install: curl -fsSL https://code.kimi.com/kimi-code/install.sh | bash" >&2
    exit 1
fi

# config.toml idempotent rendern — credentials/ NIE anfassen (eigener Grant).
cat > "$KIMI_HOME/config.toml" <<KIMI_CONF
# GENERATED by docker/kimi-host/entrypoint.sh — Hand-Edits werden beim
# nächsten Start überschrieben. credentials/ bleibt unangetastet.
default_model = "kimi-code/k3"

[thinking]
enabled = true
effort = "high"

[providers."managed:kimi-code"]
type = "kimi"
api_key = ""
base_url = "https://api.kimi.com/coding/v1"

[providers."managed:kimi-code".oauth]
storage = "file"
key = "oauth/kimi-code"

# W2.1 Turn-Signal (ADR-071) — Pfad agent-lokal, damit Marks interaktive
# Kimi-Sessions davon nichts sehen.
[[hooks]]
event = "UserPromptSubmit"
command = "printf '%s submit\n' \"\$(date +%s)\" >> $BASE/.turn-signal"
timeout = 5

[[hooks]]
event = "Stop"
command = "printf '%s stop\n' \"\$(date +%s)\" >> $BASE/.turn-signal"
timeout = 5
KIMI_CONF

if [ ! -s "$KIMI_HOME/credentials/kimi-code.json" ]; then
    echo "[kimi-host] WARNUNG: Keine Kimi-Credentials — einmalig '/login' im Sessions-Terminal ausführen."
fi

# Frische Signal-Datei beim Boot (Muster Container-Entrypoint).
: > "$BASE/.turn-signal"

# Vorhandene Session defensiv killen
tmux kill-session -t "$SESSION" 2>/dev/null || true

# extended-keys ist für kimi PFLICHT (Enter-Submit, Spike 2026-07-24).
tmux set -g extended-keys on 2>/dev/null || true

# Env für beide Windows (tmux erbt die Umgebung dieses Prozesses):
export KIMI_CODE_HOME="$KIMI_HOME"
export KIMI_BIN
export AGENT_NAME="kimi"
export MC_API_URL="${MC_API_URL:-http://localhost:8000}"
export PANE_UI_OVERRIDE="kimi"
export TURN_SIGNAL_FILE="$BASE/.turn-signal"
export TASK_LOCK_FILE="$BASE/.task-active.lock"
export MSG_QUEUE_DIR="$BASE/.msg-queue"
export MSG_ACK_DIR="$BASE/.msg-acked"
export NUDGE_STATE_FILE="$BASE/.msg-nudge-state"
export POLL_LIB_DIR="$REPO/docker/mc-agent-base/lib"
export MSG_DELIVERY_MODE="${MSG_DELIVERY_MODE:-nudge}"

# Window 0: kimi-TUI in Restart-Loop
tmux new-session -d -s "$SESSION" \
    "d=2; while true; do bash '$REPO/docker/kimi-host/start-kimi-host.sh'; echo '[kimi-host] kimi exited, restart in '\$d's...'; sleep \$d; d=\$(( d*2 > 60 ? 60 : d*2 )); done"

# Window 1: geteilter poll.sh
tmux new-window -t "$SESSION:1" \
    "d=2; while true; do bash '$REPO/docker/shared/poll.sh'; echo '[kimi-host] poll.sh exited, restart in '\$d's...'; sleep \$d; d=\$(( d*2 > 60 ? 60 : d*2 )); done"

tmux select-window -t "$SESSION:0"
echo "[kimi-host] Session '$SESSION' gestartet (Window 0 kimi, Window 1 poll)."

# PID 1 (launchd KeepAlive): Watchdog wie Boss-Host.
while true; do
    sleep 30
    if ! tmux has-session -t "$SESSION" 2>/dev/null; then
        echo "[kimi-host] tmux session weg — launchd-Restart via exit."
        exit 1
    fi
done
